export enum EnvKey {
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',

  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRES_AT = 'ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_EXPIRES_AT = 'REFRESH_TOKEN_EXPIRES_IN',
}
